#!/bin/sh

function main() {
  #设置dnsforwarder，添加wan端dns
  if [[ "$(cat /etc/config/dnsforwarder)" =~ "%wan_dns%" ]]; then
    for i in $(seq 5); do
      wan_dns="$(ifstatus wan | jsonfilter -e '@["dns-server"][0]' || echo '')"
      if [[ "$wan_dns" != "" ]]; then
        sed -i "s/%wan_dns%/${wan_dns},/" /etc/config/dnsforwarder
        break
      else
        if [[ $i == 5 ]]; then
          return 0
        else
          sleep 10s
        fi
      fi
    done
  fi
  rm -rf /etc/uci-defaults/99-dnsforwarder
}

main &
exit 1
